field.value.image_style_selector:
  type: field.value.*
  mapping:
    value:
      type: string

field.field_settings.image_style_selector:
  type: field.field_settings.*
  mapping:
    image_styles:
      type: sequence
      sequence:
        type: mapping
        mapping:
          enable:
            type: boolean
